version: '3.4'

services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  redis:
    image: redis

  messagebus:
    image: rabbitmq:3.6-management

  identity:
    image: quay.io/keycloak/keycloak:24.0.3

volumes:
  postgres_eshopdb:
