services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  redis:
    image: redis

  messagebus:
    image: rabbitmq:3.6-management

  identity:
    image: quay.io/keycloak/keycloak:24.0.3

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
      
volumes:
  postgres_eshopdb: